pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: './Discord.Addons.Hosting/Discord.Addons.Hosting.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: './Discord.Addons.Hosting/Discord.Addons.Hosting.csproj'
    arguments: --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build'
  
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: './Discord.Addons.Hosting/Discord.Addons.Hosting.csproj'   
    packDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Discord.Net.Hosting.Artifacts
  displayName: 'Publish Artifacts'
